const rec=new Set(['yogur','huevo','pollo','pescado','atun','carne','frijol','lenteja','leche','platano','manzana','guayaba','mamey','pina','frutos','espinaca','pepino','zanahoria','ensalada','tomate','cebolla','verduras','avena','tortilla','arroz','papa','tostada','aguacate','aceite']);
const label=id=>Object.values(G).flat().find(x=>x[0]===id)?.[1]||id,purchases=()=>new Set(J('da_purchases',[])),ok=(r,p=purchases())=>r.req.every(x=>p.has(x));
function tab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));if(id==='progreso')chart();scrollTo(0,0)}
$$('.tab').forEach(x=>x.onclick=()=>tab(x.dataset.tab));
function profile(){let p=J('da_profile',null);if(!p)return;['Name','Age','Height','Weight','Waist','Goal'].forEach(k=>$('#profile'+k).value=p[k.toLowerCase()]??'');$('#profileActivity').value=p.activity||1.4;let b=10*p.weight+6.25*p.height-5*p.age+5,m=b*(p.activity||1.4),c=Math.max(Math.round((b+200)/50)*50,Math.round((m-200)/50)*50),pr=Math.round(p.weight*1.7/5)*5,ratio=p.waist/p.height,h=Math.round(p.height*.5);$('#profileHeader').textContent=`${p.weight} kg → ${p.goal} kg · ${p.height} cm · cintura ${p.waist} cm`;$('#targetCalories').textContent=`≈ ${c.toLocaleString('es-MX')} kcal`;$('#targetProtein').textContent=`${pr-5}–${pr+5} g`;$('#waistRatio').textContent=ratio.toFixed(2);$('#waistGoals').innerHTML=`<span class=pill>${Math.max(p.waist-3,h)} cm</span><span class=pill>${Math.max(p.waist-6,h)} cm</span><span class=pill>${h} cm o menos</span>`}
$('#saveProfile').onclick=()=>{let p={name:$('#profileName').value.trim(),age:+$('#profileAge').value,height:+$('#profileHeight').value,weight:+$('#profileWeight').value,waist:+$('#profileWaist').value,goal:+$('#profileGoal').value,activity:+$('#profileActivity').value};if(!p.age||!p.height||!p.weight||!p.waist||!p.goal)return alert('Completa edad, estatura, peso, cintura y meta.');S('da_profile',p);profile();alert('Perfil guardado en este dispositivo.')};
function shopping(){let p=purchases(),h='';for(let[g,a]of Object.entries(G)){h+=`<h3>${g}</h3>`;for(let[id,n]of a)h+=`<div class=check><input type=checkbox class=purchase data-id=${id} id=p-${id} ${p.has(id)?'checked':''}><label for=p-${id}>${n}</label></div>`}$('#shoppingGroups').innerHTML=h;$$('.purchase').forEach(x=>x.onchange=saveShop);shopStatus();smoothies()}
function saveShop(){S('da_purchases',$$('.purchase').filter(x=>x.checked).map(x=>x.dataset.id));shopStatus();smoothies()}
function shopStatus(){let p=purchases(),prot=['yogur','huevo','pollo','pescado','atun','carne','cottage','frijol','lenteja'].filter(x=>p.has(x)).length,veg=['espinaca','pepino','jicama','zanahoria','nopales','ensalada','tomate','verduras','pico'].filter(x=>p.has(x)).length;$('#shoppingStatus').innerHTML=`Marcaste <strong>${p.size}</strong> productos. <span class=${prot<3?'status-warn':'status-good'}>${prot<3?'Marca al menos 3 proteínas.':'Buena variedad de proteína.'}</span> <span class=${veg<4?'status-warn':'status-good'}>${veg<4?'Agrega más verduras.':'Buena variedad de verduras.'}</span>`}
$('#selectRecommended').onclick=()=>{$$('.purchase').forEach(x=>x.checked=rec.has(x.dataset.id));saveShop()};$('#clearShopping').onclick=()=>{if(confirm('¿Desmarcar todo?')){$$('.purchase').forEach(x=>x.checked=false);saveShop()}};$('#copyShopping').onclick=async()=>{let t='Compra marcada:\n- '+[...purchases()].map(label).sort().join('\n- ');try{await navigator.clipboard.writeText(t);alert('Lista copiada.')}catch{prompt('Copia:',t)}};
function generate(){saveShop();let p=purchases(),by=t=>R.filter(r=>r.type===t&&ok(r,p)),closest=t=>{let candidates=R.filter(r=>r.type===t).map(r=>({r,missing:r.req.filter(x=>!p.has(x))})).sort((a,b)=>a.missing.length-b.missing.length);return candidates[0]},b=by('Desayuno'),l=by('Comida'),d=by('Cena'),s=by('Colación'),warn=[],explain=(type,list,labelText,min=1)=>{if(list.length>=min)return;let c=closest(type),missing=c?.missing.map(label).join(', ');warn.push(`${labelText}${missing?` La opción más cercana requiere: ${missing}.`:''}`)};explain('Desayuno',b,'No hay desayunos completos.');explain('Comida',l,'No hay comidas completas.');explain('Cena',d,'No hay cenas completas.');explain('Colación',s,'No hay suficientes colaciones compatibles.',2);let days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'],items=days.map((day,i)=>({day,breakfast:b[i%b.length]||null,snack1:s[i%s.length]||null,lunch:l[(i+1)%l.length]||null,snack2:s[(i+2)%s.length]||null,dinner:d[(i+1)%d.length]||null}));S('da_menu',{created:new Date().toISOString(),items,warnings:warn});menu();tab('menu')}
$('#generateMenu').onclick=$('#regenerateMenu').onclick=generate;
const meal=(n,r)=>r?`<div class=meal><div class=meal-head><strong>${n}: ${r.name}</strong><span class=tag>≈ ${r.kcal} kcal · ${r.protein} g proteína</span></div><p>${r.detail}</p></div>`:`<div class="meal unavailable"><strong>${n}:</strong> no disponible con tus compras.</div>`;
function menu(){let m=J('da_menu',null);if(!m){$('#menuOutput').innerHTML='<p>Selecciona tus compras y genera el menú.</p>';return}$('#menuSummary').textContent=`Generado ${new Date(m.created).toLocaleString('es-MX')}. Solo usa productos marcados.`;$('#menuOutput').innerHTML=m.items.map(x=>`<h3>${x.day}</h3>${meal('Desayuno',x.breakfast)}${meal('Colación 1',x.snack1)}${meal('Comida',x.lunch)}${meal('Colación 2',x.snack2)}${meal('Cena',x.dinner)}`).join('');$('#menuWarning').style.display=m.warnings.length?'block':'none';$('#menuWarning').innerHTML='<strong>Falta variedad:</strong><ul>'+m.warnings.map(x=>`<li>${x}</li>`).join('')+'</ul>'}
function smoothies(){let p=purchases();$('#smoothieOutput').innerHTML=R.filter(r=>r.type==='Desayuno'&&r.name.startsWith('Licuado')).map(r=>{let a=ok(r,p),miss=r.req.filter(x=>!p.has(x)).map(label);return`<div class="meal ${a?'':'unavailable'}"><div class=meal-head><strong>${r.name}</strong><span class=tag>${a?'Disponible':'No disponible'}</span></div><p>${r.detail}</p>${a?'':`<p class=missing>Falta: ${miss.join(', ')}</p>`}</div>`}).join('')}
$$('.work').forEach(x=>{x.checked=J('da_work',[]).includes(x.dataset.id);x.onchange=()=>S('da_work',$$('.work').filter(y=>y.checked).map(y=>y.dataset.id))});
const logs=()=>J('da_logs',[]);function renderLogs(){let a=logs().sort((x,y)=>x.date.localeCompare(y.date));$('#logRows').innerHTML=a.map(x=>`<tr><td>${x.date}</td><td>${x.weight??''}</td><td>${x.waist??''}</td><td>${x.fat??''}</td><td>${x.muscle??''}</td><td>${x.visceral??''}</td><td>${x.hunger??''}</td></tr>`).join('');chart()}
$('#saveLog').onclick=()=>{let date=$('#logDate').value,weight=+$('#logWeight').value;if(!date||!weight)return alert('Agrega fecha y peso.');let n=id=>$(id).value===''?null:+$(id).value,a=logs().filter(x=>x.date!==date);a.push({date,weight,waist:n('#logWaist'),fat:n('#logFat'),muscle:n('#logMuscle'),visceral:n('#logVisceral'),hunger:n('#logHunger')});S('da_logs',a);renderLogs();alert('Medición guardada.')};
$('#copySummary').onclick=async()=>{let a=logs().sort((x,y)=>x.date.localeCompare(y.date)).slice(-7);if(!a.length)return alert('Primero guarda una medición.');let f=a[0],e=a.at(-1),avg=k=>{let n=a.map(x=>x[k]).filter(Number.isFinite);return n.length?(n.reduce((s,v)=>s+v,0)/n.length).toFixed(1):'sin dato'},t=`Seguimiento Dieta Alex\nPeriodo: ${f.date} a ${e.date}\nPeso inicial: ${f.weight} kg\nPeso final: ${e.weight} kg\nCambio: ${(e.weight-f.weight).toFixed(1)} kg\nÚltima cintura: ${e.waist??'sin dato'} cm\nGrasa RENPHO: ${e.fat??'sin dato'} %\nMasa muscular: ${e.muscle??'sin dato'}\nHambre promedio: ${avg('hunger')}/10\nAjusta mi plan sin aumentar demasiado el hambre.`;try{await navigator.clipboard.writeText(t);alert('Resumen copiado.')}catch{prompt('Copia:',t)}};
$('#exportData').onclick=()=>{let d={version:V,profile:J('da_profile',null),purchases:[...purchases()],menu:J('da_menu',null),logs:logs(),work:J('da_work',[])},a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.href=url;a.download='dieta-alex-respaldo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{let file=e.target.files?.[0];if(!file) return;let d=JSON.parse(await file.text()),allIds=new Set(Object.values(G).flat().map(x=>x[0])),profile=d.profile,validProfile=profile===null||(profile&&typeof profile==='object'&&['age','height','weight','waist','goal','activity'].every(k=>Number.isFinite(Number(profile[k])))),purchasesValid=Array.isArray(d.purchases)&&d.purchases.every(x=>typeof x==='string'&&allIds.has(x)),logsValid=Array.isArray(d.logs)&&d.logs.every(x=>x&&typeof x.date==='string'&&Number.isFinite(Number(x.weight))),workValid=Array.isArray(d.work)&&d.work.every(x=>typeof x==='string');if(!validProfile||!purchasesValid||!logsValid||!workValid)throw new Error('Formato inválido');S('da_profile',profile);S('da_purchases',[...new Set(d.purchases)]);S('da_logs',d.logs.map(x=>({...x,weight:Number(x.weight)})));S('da_work',[...new Set(d.work)]);localStorage.removeItem('da_menu');alert('Respaldo importado. El menú se regenerará con tus compras.');location.reload()}catch{alert('Respaldo inválido. No se modificaron tus datos.')}finally{e.target.value=''}};
function chart(){let c=$('#chart'),x=c.getContext('2d'),a=logs().filter(v=>Number.isFinite(v.weight)).sort((p,q)=>p.date.localeCompare(q.date));x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);if(!a.length){$('#trend').textContent='Sin mediciones.';return}let P=48,w=c.width-2*P,h=c.height-2*P,v=a.map(z=>z.weight),mn=Math.min(...v)-.4,mx=Math.max(...v)+.4;x.strokeStyle='#d9e5de';for(let i=0;i<5;i++){let y=P+h*i/4;x.beginPath();x.moveTo(P,y);x.lineTo(P+w,y);x.stroke()}x.strokeStyle='#176b46';x.lineWidth=4;x.beginPath();a.forEach((z,i)=>{let X=P+(a.length===1?w/2:w*i/(a.length-1)),Y=P+h-(z.weight-mn)/(mx-mn)*h;i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke();$('#trend').textContent=a.length>1?`Cambio: ${(a.at(-1).weight-a[0].weight).toFixed(1)} kg entre ${a[0].date} y ${a.at(-1).date}.`:'Guarda más mediciones.'}
let promptInstall;if(matchMedia('(display-mode: standalone)').matches)$('#installBanner').style.display='none';addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptInstall=e;$('#installBanner').style.display='block'});addEventListener('appinstalled',()=>{promptInstall=null;$('#installBanner').style.display='none'});$('#installBtn').onclick=async()=>{if(promptInstall){promptInstall.prompt();await promptInstall.userChoice;promptInstall=null;$('#installBanner').style.display='none'}};if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>{if(r.waiting&&navigator.serviceWorker.controller)$('#updateBanner').style.display='block';r.addEventListener('updatefound',()=>{const worker=r.installing;if(worker)worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$('#updateBanner').style.display='block'})});setInterval(()=>r.update(),60*60*1000)}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}$('#reloadBtn').onclick=async()=>{let r=await navigator.serviceWorker.getRegistration();r?.waiting?.postMessage({type:'SKIP_WAITING'})};
$('#versionText').textContent=`Versión ${V}`;$('#logDate').value=new Date().toISOString().slice(0,10);profile();shopping();menu();renderLogs();
